# Generated by Django 2.1.7 on 2019-03-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
