# Generated by Django 2.1.7 on 2019-03-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_books'),
        ('core', '0002_auto_20190315_1605'),
    ]

    operations = [
    ]
